import path from "node:path"
import { format } from "prettier"

const root = path.resolve(import.meta.dir, "../packages/skills")
const catalog = []
for (const name of ["fluiddb-feedback", "fluiddb-memory"]) {
  const file = await Bun.file(path.join(root, "skills", name, "SKILL.md")).text()
  const frontmatter = Bun.YAML.parse(file.match(/^---\n([\s\S]+?)\n---\n/)?.[1] ?? "") as Record<string, unknown>
  if (frontmatter.name !== name || typeof frontmatter.description !== "string") throw new Error(`Invalid skill ${name}`)
  const uri = `skill://${name}/SKILL.md`
  const files = [],
    resources = []
  for (const relative of [
    ...new Bun.Glob("**/*").scanSync({ cwd: path.join(root, "skills", name), onlyFiles: true }),
  ].sort()) {
    if (!relative.endsWith(".md"))
      throw new Error(`Unsupported skill file: ${relative}; add its encoding before publishing`)
    const text = await Bun.file(path.join(root, "skills", name, relative)).text()
    const bytes = new TextEncoder().encode(text)
    const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", bytes)).toHex()
    const resourceUri = `skill://${name}/${relative}`
    resources.push({ uri: resourceUri, digest: `sha256:${digest}`, size: bytes.byteLength })
    files.push({ uri: resourceUri, mimeType: "text/markdown", text })
  }
  catalog.push({
    entry: { uri, frontmatter, resources },
    files,
  })
}
const generated = await format(
  `// Generated by bun scripts/skills.ts from skills/*/SKILL.md; do not edit.\nexport const catalog = ${JSON.stringify(catalog)}\n`,
  { parser: "typescript", semi: false, printWidth: 120 },
)
const target = Bun.file(path.join(root, "src/generated.ts"))
if (process.argv.includes("--check")) {
  if (!(await target.exists()) || (await target.text()) !== generated)
    throw new Error("Skills changed; run bun scripts/skills.ts")
} else await Bun.write(target, generated)
